import {
  ArrowRight,
  BellRing,
  CalendarDays,
  Check,
  ChevronDown,
  ClipboardCheck,
  Clock3,
  Camera,
  CookingPot,
  Eye,
  MessageCircle,
  Handshake,
  Heart,
  HeartHandshake,
  HeartPlus,
  House,
  BriefcaseBusiness,
  ListChecks,
  LockKeyhole,
  Mail,
  MapPin,
  Menu,
  MessageCircleHeart,
  Phone,
  Send,
  ShieldCheck,
  ShoppingBasket,
  Sparkles,
  Star,
  UserCheck,
  UsersRound,
  X,
} from "lucide-react";

const iconMap = {
  ArrowRight,
  BellRing,
  CalendarDays,
  Check,
  ChevronDown,
  ClipboardCheck,
  Clock3,
  CookingPot,
  Eye,
  Facebook: MessageCircle,
  Handshake,
  Heart,
  HeartHandshake,
  HeartPlus,
  House,
  Instagram: Camera,
  Linkedin: BriefcaseBusiness,
  ListChecks,
  LockKeyhole,
  Mail,
  MapPin,
  Menu,
  MessageCircleHeart,
  Phone,
  Send,
  ShieldCheck,
  ShoppingBasket,
  Sparkles,
  Star,
  UserCheck,
  UsersRound,
  X,
};

export function Icon({ name, ...props }) {
  const Component = iconMap[name] || Heart;
  return <Component aria-hidden="true" focusable="false" {...props} />;
}
